# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - commit-message:
      include: "scope"
      prefix: "composer"
    directory: "/"
    labels:
      - "dependency"
    open-pull-requests-limit: 10
    package-ecosystem: "composer"
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"

  - commit-message:
      include: "scope"
      prefix: "composer"
    directory: "tools/"
    labels:
      - "tools dependency"
    open-pull-requests-limit: 5
    package-ecosystem: "composer"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"